### ISSUE TITLE
Testdata not available

### ISSUE THREAD

**Issue by Radiomix2000** [falkenber9/falcon#2]
Is this testdata still necessary?

git clone --recurse-submodules https://github.com/falkenber9/falcon.git
Cloning into 'falcon'...
remote: Enumerating objects: 577, done.
remote: Counting objects: 100% (577/577), done.
remote: Compressing objects: 100% (257/257), done.
remote: Total 1181 (delta 354), reused 505 (delta 315), pack-reused 604
Receiving objects: 100% (1181/1181), 6.78 MiB | 1.79 MiB/s, done.
Resolving deltas: 100% (645/645), done.
Submodule '_gitlab-ci/testdata' (https://github.com/falkenber9/falcon-testdata.git) registered for path '_gitlab-ci/testdata'
Cloning into '/home/xxxx/falcon/_gitlab-ci/testdata'...
Username for 'https://github.com':
Password for 'https://xxxxxx@mail.ee@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/falkenber9/falcon-testdata.git/' not found
fatal: clone of 'https://github.com/falkenber9/falcon-testdata.git' into submodule path '/home/xxxxx/falcon/_gitlab-ci/testdata' failed
Failed to clone '_gitlab-ci/testdata'. Retry scheduled
Cloning into '/home/xxxxx/falcon/_gitlab-ci/testdata'...
Username for 'https://github.com':
Password for 'https://xxxxxx@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/falkenber9/falcon-testdata.git/' not found
fatal: clone of 'https://github.com/falkenber9/falcon-testdata.git' into submodule path '/home/Armin/falcon/_gitlab-ci/testdata' failed
Failed to clone '_gitlab-ci/testdata' a second time, aborting

**Comment by falkenber9** [comment]
Hello,

it is not required for normal usage. Just omit the ``--recurse-submodules`` flag.
The testdata repository is part of a private CI chain located in the institute.
Due to the huge size of several GB, it is maintained as an external project and is included as an *optional* submodule.

Nevertheless, I will keep this issue open until I have checked for other ways to include those tests in a way that is convenient to us and does not confuse the normal users.

Best regards

**Comment by falkenber9** [comment]
Submodule with testdata has been removed in release v1.3.0.
CI now uses a cache instead.
